# Generated by Django 5.2.14 on 2026-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
