# Generated by Django 5.2.14 on 2026-05-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='venta',
            name='credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='debito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='efectivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='transferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
