# Generated by Django 5.2.14 on 2026-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_fijos_por_kg', models.DecimalField(decimal_places=2, default=480, max_digits=10)),
                ('gastos_variables_por_kg', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
            ],
        ),
    ]
