# Generated by Django 5.2.14 on 2026-05-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_fijos_por_kg', models.DecimalField(decimal_places=2, default=480.0, max_digits=10)),
                ('gastos_variables_por_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('iva_por_defecto', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('margen_objetivo', models.DecimalField(decimal_places=2, default=25.0, help_text='Margen esperado (%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración de costeo',
                'verbose_name_plural': 'Configuraciones de costeo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo compra/kg')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
