# Generated by Django 5.2.14 on 2026-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_fijos_por_kg', models.DecimalField(decimal_places=2, default=480.0, help_text='Gastos fijos (en $) por cada kg vendido', max_digits=10)),
                ('gastos_variables_por_kg', models.DecimalField(decimal_places=2, default=50.0, help_text='Gastos variables (en $) por cada kg vendido', max_digits=10)),
                ('iva_por_defecto', models.DecimalField(decimal_places=2, default=19.0, help_text='IVA estándar (en %)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración de costeo',
                'verbose_name_plural': 'Configuraciones de costeo',
            },
        ),
    ]
