# Generated by Django 5.2.14 on 2026-05-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_configuracioncosteo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracioncosteo',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='gastos_fijos_por_kg',
            field=models.DecimalField(decimal_places=2, default=480.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='gastos_variables_por_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='iva_por_defecto',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
