# Generated by Django 5.2.14 on 2026-05-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_configuracioncosteo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='configuracioncosteo',
            options={'verbose_name': 'Configuración de costeo', 'verbose_name_plural': 'Configuraciones de costeo'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_neto',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta/kg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='gastos_fijos_por_kg',
            field=models.DecimalField(decimal_places=2, default=480.0, max_digits=10, verbose_name='Gastos fijos por kg'),
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='gastos_variables_por_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Gastos variables por kg'),
        ),
        migrations.AlterField(
            model_name='configuracioncosteo',
            name='iva_por_defecto',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='IVA por defecto (%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo compra/kg'),
        ),
    ]
